import MEVShieldCore from 0xc13b08053be24e87
import SentinelVaultFinal from 0xc13b08053be24e87
import SentinelInterfaces from 0x136b642d0aa31ca9
import LiquidStakingStrategy from 0xc13b08053be24e87
import YieldFarmingStrategy from 0xc13b08053be24e87
import ArbitrageStrategy from 0xc13b08053be24e87
import YieldOracle from 0xc13b08053be24e87

// ── Auto Execute Vault — Phase 5 ──
// Called by the strategy-keeper Netlify function for automated vault execution.
// Unlike mev_reveal.cdc (user-initiated), this is designed for keeper automation:
//   - commitHash generated server-side by the keeper using lib/mev-hash.ts
//   - Works on any vault — keeper iterates all vaults due for execution
//   - If vault is paused, transaction succeeds but silently skips execution
//   - Full MEV protection (Layers 1-4) still applied
//
// Parameters:
//   ownerId      — address of the vault owner
//   vaultId      — ID of the vault to execute
//   commitHash   — [UInt8] SHA3-256 hash generated by keeper
//   nonce        — UInt64 nonce used to generate the hash
//   expectedAPY  — current APY from oracle (keeper fetches this)
//
transaction(
    ownerId: Address,
    vaultId: UInt64,
    commitHash: [UInt8],
    nonce: UInt64,
    expectedAPY: UFix64
) {
    prepare(signer: auth(BorrowValue) &Account) {
        assert(commitHash.length == 32, message: "commitHash must be 32 bytes")

        // Borrow the vault owner's account (keeper acts as proposer, not owner)
        let ownerAccount = getAccount(ownerId)
        let collection = ownerAccount.capabilities
            .borrow<&{SentinelVaultFinal.CollectionPublic}>(
                SentinelVaultFinal.VaultCollectionPublicPath
            ) ?? panic("No public collection for owner: ".concat(ownerId.toString()))

        // Check vault is still active and due before executing
        let vaultInfos = collection.getVaultInfos()
        var targetInfo: SentinelVaultFinal.VaultInfo? = nil
        for info in vaultInfos {
            if info.id == vaultId { targetInfo = info; break }
        }
        guard let vaultInfo = targetInfo else {
            panic("Vault #".concat(vaultId.toString()).concat(" not found"))
        }
        if !vaultInfo.isActive {
            // Vault is paused — skip silently, return without panicking
            return
        }

        let now = getCurrentBlock().timestamp
        let isDue = vaultInfo.nextScheduledExecution == nil || now >= vaultInfo.nextScheduledExecution!
        if !isDue {
            // Not due yet — skip without failing (keeper may have called slightly early)
            return
        }

        // Commit the hash (Layer 1 MEV protection)
        MEVShieldCore.createCommit(
            vaultId: vaultId,
            commitHash: commitHash,
            protectionLevel: 3,
            committedBy: ownerId
        )

        // Reveal and enqueue for execution (Layers 2-4)
        let deadlineBlock = getCurrentBlock().height + MEVShieldCore.getMEVCommitBlocks()
        MEVShieldCore.revealExecution(
            vaultId: vaultId,
            commitHash: commitHash,
            nonce: nonce,
            amount: 0.0,          // keeper uses 0; vault reads its own balance
            strategyId: vaultInfo.strategyId,
            deadlineBlock: deadlineBlock,
            expectedAPY: expectedAPY,
            slippageBps: 300.0
        )

        // NOTE: keeper cannot borrow with auth entitlements from the owner's account.
        // The vault must expose a keeper-callable execution path or the owner must
        // pre-authorize. For now, keeper uses performStrategy() via the public path.
        // See docs/KEEPER_AUTH.md for the full authorization model.
    }
}
