// PartnerRegistry — B2B partner management and revenue sharing for Flow Sentinel
//
// Partners (apps, DAOs, treasury tools) integrate the Sentinel SDK and earn
// a share of protocol fees generated by vaults created through their integration.
//
// Architecture:
//   - Each partner gets a unique ID and configurable fee split (e.g., 70% partner / 30% Flow Sentinel)
//   - When a vault is created with a partnerId, the protocol fee on deposits is split
//   - Partners can track TVL, vaults created, and fees earned through on-chain queries
//   - The SDK passes partnerId during vault creation for automatic attribution
//
// Flow Sentinel keeps 30% of the protocol fee; partners earn 70%.
// Default split: 7000 bps (70%) to partner, 3000 bps (30%) to protocol.

access(all) contract PartnerRegistry {

    // ── Events ──
    access(all) event PartnerRegistered(partnerId: UInt64, name: String, owner: Address, feeShareBps: UInt64)
    access(all) event PartnerUpdated(partnerId: UInt64, name: String, isActive: Bool)
    access(all) event VaultAttributed(vaultId: UInt64, partnerId: UInt64, owner: Address)
    access(all) event PartnerFeeDistributed(partnerId: UInt64, vaultId: UInt64, feeAmount: UFix64, partnerShare: UFix64, sentinelShare: UFix64)
    access(all) event FeeShareUpdated(partnerId: UInt64, oldShareBps: UInt64, newShareBps: UInt64)

    // ── Constants ──
    /// Default partner fee share: 70% of protocol fee (7000 bps)
    access(all) let defaultPartnerFeeShareBps: UInt64
    /// Protocol retains: 30% of protocol fee (3000 bps)
    access(all) let defaultSentinelFeeShareBps: UInt64
    /// Max fee share allowed (95%)
    access(all) let maxPartnerFeeShareBps: UInt64
    /// Max partner name length
    access(all) let maxNameLength: UInt64

    // ── Storage ──
    access(self) var partners: {UInt64: Partner}
    access(self) var partnerCounter: UInt64
    access(self) var partnerByOwner: {Address: UInt64}
    access(self) var vaultAttribution: {UInt64: UInt64}  // vaultId → partnerId

    // ── Structs ──
    access(all) struct Partner {
        access(all) let id: UInt64
        access(all) let name: String
        access(all) let owner: Address
        access(all) var feeShareBps: UInt64        // partner's share in bps (e.g., 7000 = 70%)
        access(all) var isActive: Bool
        access(all) var totalVaults: UInt64         // vaults created through this partner
        access(all) var totalTVL: UFix64            // total value locked across partner vaults
        access(all) var totalFeesEarned: UFix64     // total fees earned by partner
        access(all) var registeredAt: UFix64        // block timestamp

        init(id: UInt64, name: String, owner: Address, feeShareBps: UInt64) {
            pre {
                name.length <= PartnerRegistry.maxNameLength: "Partner name too long (max 64 chars)"
                feeShareBps <= PartnerRegistry.maxPartnerFeeShareBps: "Fee share exceeds max (9500 bps = 95%)"
            }
            self.id = id
            self.name = name
            self.owner = owner
            self.feeShareBps = feeShareBps
            self.isActive = true
            self.totalVaults = 0
            self.totalTVL = 0.0
            self.totalFeesEarned = 0.0
            self.registeredAt = getCurrentBlock().timestamp
        }
    }

    access(all) struct PartnerPublic {
        access(all) let id: UInt64
        access(all) let name: String
        access(all) let owner: Address
        access(all) let feeShareBps: UInt64
        access(all) let isActive: Bool
        access(all) let totalVaults: UInt64
        access(all) let totalTVL: UFix64
        access(all) let totalFeesEarned: UFix64

        init(p: Partner) {
            self.id = p.id
            self.name = p.name
            self.owner = p.owner
            self.feeShareBps = p.feeShareBps
            self.isActive = p.isActive
            self.totalVaults = p.totalVaults
            self.totalTVL = p.totalTVL
            self.totalFeesEarned = p.totalFeesEarned
        }
    }

    access(all) struct FeeSplit {
        access(all) let partnerShare: UFix64
        access(all) let sentinelShare: UFix64

        init(partnerShare: UFix64, sentinelShare: UFix64) {
            self.partnerShare = partnerShare
            self.sentinelShare = sentinelShare
        }
    }

    // ── Initialization ──
    init() {
        self.defaultPartnerFeeShareBps = 7000       // 70% to partner
        self.defaultSentinelFeeShareBps = 3000      // 30% to Flow Sentinel
        self.maxPartnerFeeShareBps = 9500           // 95% max
        self.maxNameLength = 64
        self.partners = {}
        self.partnerCounter = 0
        self.partnerByOwner = {}
        self.vaultAttribution = {}
    }

    // ── Admin Functions ──

    /// Register a new partner app
    access(account) fun registerPartner(name: String, owner: Address, feeShareBps: UInt64): UInt64 {
        pre {
            self.partnerByOwner[owner] == nil: "Owner already registered as a partner"
            feeShareBps <= self.maxPartnerFeeShareBps: "Fee share exceeds max (9500 bps)"
            name.length > 0: "Name cannot be empty"
            name.length <= self.maxNameLength: "Name too long"
        }
        let id = self.partnerCounter
        let partner = Partner(id: id, name: name, owner: owner, feeShareBps: feeShareBps)
        self.partners[id] = partner
        self.partnerByOwner[owner] = id
        self.partnerCounter = self.partnerCounter + 1
        emit PartnerRegistered(partnerId: id, name: name, owner: owner, feeShareBps: feeShareBps)
        return id
    }

    /// Update partner status (activate/deactivate)
    access(account) fun setPartnerActive(partnerId: UInt64, isActive: Bool) {
        pre { self.partners[partnerId] != nil: "Partner not found" }
        let partner = &self.partners[partnerId] as! &Partner
        partner.isActive = isActive
        emit PartnerUpdated(partnerId: partnerId, name: partner.name, isActive: isActive)
    }

    /// Update partner fee share
    access(account) fun setPartnerFeeShare(partnerId: UInt64, newFeeShareBps: UInt64) {
        pre {
            self.partners[partnerId] != nil: "Partner not found"
            newFeeShareBps <= self.maxPartnerFeeShareBps: "Fee share exceeds max (9500 bps)"
        }
        let partner = &self.partners[partnerId] as! &Partner
        let oldShareBps = partner.feeShareBps
        partner.feeShareBps = newFeeShareBps
        emit FeeShareUpdated(partnerId: partnerId, oldShareBps: oldShareBps, newShareBps: newFeeShareBps)
    }

    // ── Public Functions (callable from SentinelVaultFinal) ──

    /// Attribute a vault to a partner — called during vault creation
    access(all) fun attributeVault(vaultId: UInt64, partnerId: UInt64) {
        if let partner = &self.partners[partnerId] as &Partner? {
            if !partner.isActive {
                panic("Partner is not active")
            }
            self.vaultAttribution[vaultId] = partnerId
            partner.totalVaults = partner.totalVaults + 1
            emit VaultAttributed(vaultId: vaultId, partnerId: partnerId, owner: partner.owner)
        }
    }

    /// Update partner TVL (called during deposit/withdrawal)
    access(all) fun updatePartnerTVL(vaultId: UInt64, delta: UFix64, isDeposit: Bool) {
        if let partnerId = self.vaultAttribution[vaultId] {
            if let partner = &self.partners[partnerId] as &Partner? {
                if isDeposit {
                    partner.totalTVL = partner.totalTVL + delta
                } else {
                    if delta >= partner.totalTVL {
                        partner.totalTVL = 0.0
                    } else {
                        partner.totalTVL = partner.totalTVL - delta
                    }
                }
            }
        }
    }

    /// Distribute protocol fee between partner and protocol
    /// Returns FeeSplit with partnerShare and sentinelShare
    access(all) fun distributeFee(vaultId: UInt64, grossFeeAmount: UFix64): FeeSplit {
        if let partnerId = self.vaultAttribution[vaultId] {
            if let partner = &self.partners[partnerId] as &Partner? {
                if partner.isActive && grossFeeAmount > 0.0 {
                    let sentinelBps = 10000 - partner.feeShareBps
                    let partnerShare = grossFeeAmount * UFix64(partner.feeShareBps) / 10000.0
                    let sentinelShare = grossFeeAmount * UFix64(sentinelBps) / 10000.0
                    partner.totalFeesEarned = partner.totalFeesEarned + partnerShare
                    emit PartnerFeeDistributed(
                        partnerId: partnerId, vaultId: vaultId,
                        feeAmount: grossFeeAmount,
                        partnerShare: partnerShare,
                        sentinelShare: sentinelShare
                    )
                    return FeeSplit(partnerShare: partnerShare, sentinelShare: sentinelShare)
                }
            }
        }
        // No partner attribution — all fee goes to protocol
        return FeeSplit(partnerShare: 0.0, sentinelShare: grossFeeAmount)
    }

    // ── Query Functions ──

    /// Get partner info by ID
    access(all) fun getPartner(partnerId: UInt64): PartnerPublic? {
        if let p = self.partners[partnerId] {
            return PartnerPublic(p: p)
        }
        return nil
    }

    /// Get partner ID by owner address
    access(all) fun getPartnerByOwner(owner: Address): UInt64? {
        return self.partnerByOwner[owner]
    }

    /// Get all partners
    access(all) fun getAllPartners(): [PartnerPublic] {
        var result: [PartnerPublic] = []
        for id in self.partners.keys {
            if let p = self.partners[id] {
                result.append(PartnerPublic(p: p))
            }
        }
        return result
    }

    /// Get total partner count
    access(all) fun getPartnerCount(): UInt64 {
        return self.partnerCounter
    }

    /// Get partner ID for a vault
    access(all) fun getVaultPartner(vaultId: UInt64): UInt64? {
        return self.vaultAttribution[vaultId]
    }

    /// Get all vault IDs attributed to a partner
    access(all) fun getPartnerVaults(partnerId: UInt64): [UInt64] {
        var vaults: [UInt64] = []
        for id in self.vaultAttribution.keys {
            if self.vaultAttribution[id] == partnerId {
                vaults.append(id)
            }
        }
        return vaults
    }

    /// Get aggregate partner stats
    access(all) fun getPartnerStats(): {String: AnyStruct} {
        var totalVaults: UInt64 = 0
        var totalTVL: UFix64 = 0.0
        var totalFeesEarned: UFix64 = 0.0
        var activePartners: UInt64 = 0
        for id in self.partners.keys {
            if let p = self.partners[id] {
                totalVaults = totalVaults + p.totalVaults
                totalTVL = totalTVL + p.totalTVL
                totalFeesEarned = totalFeesEarned + p.totalFeesEarned
                if p.isActive {
                    activePartners = activePartners + 1
                }
            }
        }
        return {
            "totalPartners": self.partnerCounter,
            "activePartners": activePartners,
            "totalVaults": totalVaults,
            "totalTVL": totalTVL,
            "totalFeesEarned": totalFeesEarned
        }
    }
}
